export const vehicle_data = [
  {
    slug: "lamborghini-huracan-evo-spyder",
    display_name: "Lamborghini Huracán Evo Spyder",
    brand: "Lamborghini",
    model: "Huracán",
    variant: "Evo Spyder",
    model_year: 2024,
    category: "Supercar",
    tags: ["supercar", "convertible", "performance"],
    location_default: "Dubai",
    main_image: null,
    gallery_images: [],
    thumbnail: null,
    description:
      "A thrilling open-top supercar with razor-sharp handling and V10 roar.",
    long_description:
      "The 2024 Lamborghini Huracán Evo Spyder combines brutal performance with drop-top freedom. Its naturally aspirated 5.2L V10 delivers explosive power, while active aerodynamics and rear-wheel steering ensure precision on any road. Perfect for high-adrenaline drives in Dubai's sun.",
    features: [
      "Convertible soft top",
      "LMS rear-wheel steering",
      "ALA 2.0 active aerodynamics",
      "7-speed dual-clutch transmission",
      "Carbon-ceramic brakes",
      "Bang & Olufsen audio",
      "Advanced driver aids (LDW, ACC)",
    ],
    highlights: [
      "0-100 km/h in 3.1 seconds",
      "Top speed over 324 km/h",
      "Naturally aspirated V10 engine",
      "Track-ready chassis tuning",
    ],
    why_choose: [
      "Unmatched V10 soundtrack with roof down",
      "Exotic Italian design turns heads",
      "Balances road comfort and racetrack prowess",
      "Premium rental value in luxury markets like Dubai",
    ],
    specs: {
      passengers: 2,
      luggage: 1,
      transmission: "7-speed Dual-Clutch Automatic",
      doors: 2,
      engine: "5.2L V10 Naturally Aspirated",
      fuel_type: "Petrol",
      horsepower: "640 HP",
      acceleration: "3.1s 0-100 km/h",
      top_speed: "324 km/h",
      drive_type: "AWD",
    },
    has_chauffeur: false,
  },
  {
    slug: "ferrari-488-pista",
    display_name: "Ferrari 488 Pista",
    brand: "Ferrari",
    model: "488",
    variant: "Pista",
    model_year: 2019,
    category: "Supercar",
    tags: ["supercar", "track-focused", "luxury"],
    location_default: "Dubai",
    main_image: "string",
    gallery_images: ["string"],
    thumbnail: null,
    description:
      "Ultimate track-bred Ferrari 488 with extreme performance engineering.",
    long_description:
      "The Ferrari 488 Pista is the pinnacle of mid-engine V8 supercars, derived directly from Ferrari's motorsport technology. Its twin-turbo 3.9L V8 produces 720 HP with F1-derived aerodynamics generating massive downforce. Extensive use of carbon fiber makes it 90kg lighter than the standard 488 GTB while retaining road usability.",
    features: [
      "Active aerodynamics with S-Duct",
      "Magnetorheological dampers",
      "F1-Trac traction control",
      "7-speed dual-clutch transmission",
      "Carbon-ceramic brakes",
      "Multimatic ASSI shocks",
      "EPS electronic power steering",
    ],
    highlights: [
      "720 HP twin-turbo V8",
      "2.85s 0-100 km/h acceleration",
      "340 km/h top speed",
      "1,360 kg dry weight",
    ],
    why_choose: [
      "Track performance matching GT3 race cars",
      "Most powerful non-hybrid V8 Ferrari ever",
      "Rare limited-production model",
      "Iconic Ferrari driving purity",
    ],
    specs: {
      passengers: 2,
      luggage: 1,
      transmission: "7-speed DCT Automatic",
      doors: 2,
      engine: "3.9L V8 Twin-Turbo",
      fuel_type: "Petrol",
      horsepower: "720 HP",
      acceleration: "2.85s 0-100 km/h",
      top_speed: "340 km/h",
      drive_type: "RWD",
    },
    has_chauffeur: false,
  },
  {
    slug: "lamborghini-urus",
    display_name: "Lamborghini Urus",
    brand: "Lamborghini",
    model: "Urus",
    variant: "S",
    model_year: 2024,
    category: "SUV",
    tags: ["suv", "performance", "luxury"],
    location_default: "Dubai",
    main_image: "string",
    gallery_images: ["string"],
    thumbnail: null,
    description:
      "World's fastest production SUV combining supercar performance with luxury utility.",
    long_description:
      "The 2024 Lamborghini Urus redefines the super SUV category with its twin-turbo V8 power, seating for five, and Lamborghini dynamics. Capable of 0-100 km/h in just 3.6 seconds with a 305 km/h top speed, it blends track capability, daily usability, and exotic styling. Advanced torque-vectoring AWD and multiple driving modes including off-road settings make it supremely versatile.",
    features: [
      "8-speed automatic transmission",
      "Torque-vectoring all-wheel drive",
      "Active air suspension",
      "Carbon-ceramic brakes available",
      "23-inch wheel options",
      "14-way power-adjustable seats",
      "17.3-inch central touchscreen",
      "Bang & Olufsen 21-speaker audio",
      "Night vision camera",
      "Rear-seat entertainment screens",
    ],
    highlights: [
      "641 HP twin-turbo V8",
      "3.6s 0-100 km/h acceleration",
      "305 km/h top speed",
      "5-passenger luxury seating",
      "850 kg towing capacity",
    ],
    why_choose: [
      "Supercar performance with family practicality",
      "Most powerful SUV on sale",
      "Iconic Lamborghini styling everywhere",
      "Versatile for city, track, and desert",
      "Best-in-class resale value",
    ],
    specs: {
      passengers: 5,
      luggage: 3,
      transmission: "8-speed Automatic",
      doors: 4,
      engine: "4.0L V8 Twin Turbo",
      fuel_type: "Petrol",
      horsepower: "641 HP",
      acceleration: "3.6s 0-100 km/h",
      top_speed: "305 km/h",
      drive_type: "AWD",
    },
    has_chauffeur: false,
  },
  {
    slug: "lamborghini-huracan-evo",
    display_name: "Lamborghini Huracán EVO",
    brand: "Lamborghini",
    model: "Huracán",
    variant: "EVO",
    model_year: 2024,
    category: "Supercar",
    tags: ["supercar", "coupe", "performance"],
    location_default: "Dubai",
    main_image: "string",
    gallery_images: ["string"],
    thumbnail: null,
    description:
      "Evolution of Lamborghini's V10 supercar with refined aerodynamics and electronics.",
    long_description:
      "The Lamborghini Huracán EVO represents the latest evolution of Lamborghini's entry-level supercar, featuring advanced aerodynamics, rear-wheel steering, and LDVI (Lamborghini Dinamica Veicolo Integrata) chassis control. Its naturally aspirated 5.2L V10 delivers 640 HP through a lightning-fast 7-speed dual-clutch transmission, achieving 0-100 km/h in 2.9 seconds with a 325+ km/h top speed. The EVO transforms the Huracán into the most complete and capable version yet.",
    features: [
      "ALA 2.0 active aerodynamics",
      "Rear-wheel steering (LMS)",
      "LDVI integrated vehicle dynamics",
      "7-speed LDF dual-clutch transmission",
      "Carbon-ceramic brakes",
      "Magnetorheological suspension",
      "ANIMA driving mode selector",
      "12.3-inch digital cockpit",
      "8.4-inch central touchscreen",
      "Bang & Olufsen sound system",
    ],
    highlights: [
      "640 HP naturally aspirated V10",
      "2.9s 0-100 km/h acceleration",
      "325+ km/h top speed",
      "42 kg more downforce than standard Huracán",
    ],
    why_choose: [
      "Iconic Lamborghini V10 soundtrack",
      "Balances road comfort with track precision",
      "Advanced electronics make it accessible yet thrilling",
      "Timeless angular design language",
      "Strong rental demand in luxury markets",
    ],
    specs: {
      passengers: 2,
      luggage: 1,
      transmission: "7-speed Dual-Clutch Automatic",
      doors: 2,
      engine: "5.2L V10 Naturally Aspirated",
      fuel_type: "Petrol",
      horsepower: "640 HP",
      acceleration: "2.9s 0-100 km/h",
      top_speed: "325 km/h",
      drive_type: "AWD",
    },
    has_chauffeur: false,
  },
  {
    slug: "ferrari-portofino",
    display_name: "Ferrari Portofino",
    brand: "Ferrari",
    model: "Portofino",
    variant: "M",
    model_year: 2020,
    category: "Convertible",
    tags: ["convertible", "gt", "luxury"],
    location_default: "Dubai",
    main_image: "string",
    gallery_images: ["string"],
    thumbnail: null,
    description:
      "Ferrari's versatile V8 grand tourer with retractable hardtop.",
    long_description:
      "The Ferrari Portofino serves as Ferrari's most accessible grand tourer, blending supercar performance with everyday usability. Its 3.9L twin-turbo V8 produces 612 HP in M specification, launching from 0-100 km/h in 3.45 seconds with a 320+ km/h top speed. The innovative retractable hardtop operates in 14 seconds, allowing open-air cruising while maintaining coupe security and refinement.",
    features: [
      "Retractable hardtop (14s operation)",
      "7-speed dual-clutch transmission (8-speed in M)",
      "Electronic differential (E-Diff3)",
      "Magnetorheological suspension",
      "Carbon-ceramic brakes",
      "Side Slip Control 6.0",
      "10.25-inch central touchscreen",
      "Active aerodynamics",
      "Electric power steering",
      "Ferrari Source audio system",
    ],
    highlights: [
      "612 HP twin-turbo V8 (Portofino M)",
      "3.45s 0-100 km/h acceleration",
      "320+ km/h top speed",
      "14-second roof operation at speeds up to 50 km/h",
    ],
    why_choose: [
      "Perfect balance of GT comfort and sports car thrills",
      "Retractable hardtop versatility for any weather",
      "More accessible than mid-engine Ferraris",
      "Excellent for long-distance cruising",
      "Strong presence in luxury rental markets",
    ],
    specs: {
      passengers: 4,
      luggage: 2,
      transmission: "7-speed Dual-Clutch Automatic",
      doors: 2,
      engine: "3.9L V8 Twin-Turbo",
      fuel_type: "Petrol",
      horsepower: "612 HP",
      acceleration: "3.45s 0-100 km/h",
      top_speed: "320 km/h",
      drive_type: "RWD",
    },
    has_chauffeur: false,
  },
  {
    slug: "mercedes-g63",
    display_name: "Mercedes-AMG G 63",
    brand: "Mercedes-Benz",
    model: "G-Class",
    variant: "AMG G 63",
    model_year: 2026,
    category: "SUV",
    tags: ["suv", "luxury", "offroad", "amg"],
    location_default: "Dubai",
    main_image: "string",
    gallery_images: ["string"],
    thumbnail: null,
    description:
      "Iconic boxy luxury SUV with monstrous V8 performance and legendary off-road capability.",
    long_description:
      "The Mercedes-AMG G 63 transforms the legendary G-Class into a 577-hp super SUV that conquers both desert dunes and city streets. Its hand-built 4.0L twin-turbo V8 delivers supercar acceleration while retaining three locking differentials and 241mm ground clearance for serious off-roading. The ultimate status symbol combines brutal power, opulent luxury, and unmistakable boxy styling.",
    features: [
      "AMG Performance 4.0L V8 biturbo",
      "9-speed AMG Speedshift automatic",
      "AMG Ride Control adaptive suspension",
      "Three locking differentials",
      "241mm ground clearance",
      "22-inch AMG forged wheels",
      "Nappa leather/AMG Performance seats",
      "Burmester High-End 3D surround sound",
      "12.3-inch dual digital displays",
      "Active ambient lighting (64 colors)",
    ],
    highlights: [
      "577 HP twin-turbo V8",
      "4.2s 0-100 km/h acceleration",
      "850 Nm torque",
      "900+ kg towing capacity",
      "240 km/h top speed (limited)",
    ],
    why_choose: [
      "Unmatched combination of luxury and off-road ability",
      "Iconic design never goes out of style",
      "AMG V8 soundtrack with Drift Mode",
      "Supreme status symbol worldwide",
      "Excellent resale value",
    ],
    specs: {
      passengers: 5,
      luggage: 3,
      transmission: "9-speed Automatic",
      doors: 5,
      engine: "4.0L V8 Twin-Turbo",
      fuel_type: "Petrol",
      horsepower: "577 HP",
      acceleration: "4.2s 0-100 km/h",
      top_speed: "240 km/h",
      drive_type: "4WD",
    },
    has_chauffeur: false,
  },
  {
    slug: "porsche-911-targa-4s",
    display_name: "Porsche 911 Carrera Targa 4S",
    brand: "Porsche",
    model: "911",
    variant: "Carrera Targa 4S",
    model_year: 2026,
    category: "Sports",
    tags: ["sports car", "targa", "performance", "luxury"],
    location_default: "Dubai",
    main_image: "string",
    gallery_images: ["string"],
    thumbnail: null,
    description:
      "High-performance Porsche 911 Targa with AWD, turbocharged power, and signature open roof.",
    long_description:
      "The Porsche 911 Carrera Targa 4S elevates the Targa experience with 443 horsepower from its 3.0L twin-turbo flat-six engine and all-wheel drive. Achieving 0-100 km/h in just 3.4 seconds, it combines blistering acceleration with the unique Targa roof's open-air freedom. Wider bodywork, advanced PASM suspension, and rear-axle steering deliver phenomenal handling precision.",
    features: [
      "Targa roof system (19s operation)",
      "Porsche Traction Management AWD",
      "8-speed PDK transmission",
      "PASM adaptive sports suspension",
      "Rear-axle steering",
      "Porsche Torque Vectoring Plus",
      "21-inch RS Spyder design wheels",
      "Sport Chrono package",
      "10.9-inch PCM infotainment",
      "Bose surround sound",
    ],
    highlights: [
      "443 HP twin-turbo flat-six",
      "3.4s 0-100 km/h acceleration",
      "304 km/h top speed",
      "Porsche Active Suspension Management",
    ],
    why_choose: [
      "More powerful than standard Targa 4",
      "All-wheel drive traction in all conditions",
      "Wider track for superior cornering",
      "Ultimate open-air sports car experience",
      "Exceptional collector appreciation",
    ],
    specs: {
      passengers: 4,
      luggage: 2,
      transmission: "8-speed PDK Automatic",
      doors: 2,
      engine: "3.0L Flat-6 Twin-Turbo",
      fuel_type: "Petrol",
      horsepower: "443 HP",
      acceleration: "3.4s 0-100 km/h",
      top_speed: "304 km/h",
      drive_type: "AWD",
    },
    has_chauffeur: false,
  },
  {
    slug: "audi-r8",
    display_name: "Audi R8 V10 Performance",
    brand: "Audi",
    model: "R8",
    variant: "V10 Performance",
    model_year: 2024,
    category: "Supercar",
    tags: ["supercar", "mid-engine", "v10"],
    location_default: "Dubai",
    main_image: "string",
    gallery_images: ["string"],
    thumbnail: null,
    description:
      "Mid-engine supercar sharing Lamborghini Huracán DNA with howling naturally aspirated V10.",
    long_description:
      "The Audi R8 V10 Performance delivers 620 horsepower from its hand-built 5.2L naturally aspirated V10 engine, achieving 0-100 km/h in 3.1 seconds. Built on the same platform as the Lamborghini Huracán, it combines Quattro all-wheel drive grip with supercar exoticism and everyday usability. Audi's swan song supercar emphasizes analog driving purity with digital precision.",
    features: [
      "5.2L naturally aspirated V10",
      "7-speed S tronic dual-clutch",
      "Quattro all-wheel drive",
      "Magnetic ride adaptive suspension",
      "Carbon-ceramic brakes",
      "20-inch forged alloy wheels",
      "Audi Virtual Cockpit",
      "Bang & Olufsen 13-speaker audio",
      "Laser LED Matrix headlights",
      "Alcantara/leather performance seats",
    ],
    highlights: [
      "620 HP naturally aspirated V10",
      "3.1s 0-100 km/h acceleration",
      "330 km/h top speed",
      "Shared platform with Lamborghini Huracán",
    ],
    why_choose: [
      "One of last pure V10 supercars",
      "Perfect supercar daily driver balance",
      "Unmatched Quattro traction",
      "R8 GT variant offers 30 more HP",
      "Excellent used value appreciation",
    ],
    specs: {
      passengers: 2,
      luggage: 1,
      transmission: "7-speed Dual-Clutch Automatic",
      doors: 2,
      engine: "5.2L V10 Naturally Aspirated",
      fuel_type: "Petrol",
      horsepower: "620 HP",
      acceleration: "3.1s 0-100 km/h",
      top_speed: "330 km/h",
      drive_type: "AWD",
    },
    has_chauffeur: false,
  },
  {
    slug: "audi-rs6",
    display_name: "Audi RS6 Avant Performance",
    brand: "Audi",
    model: "RS6",
    variant: "Avant Performance",
    model_year: 2026,
    category: "Luxury",
    tags: ["wagon", "performance", "superwagon", "luxury"],
    location_default: "Dubai",
    main_image: "string",
    gallery_images: ["string"],
    thumbnail: null,
    description:
      "621-hp twin-turbo V8 super wagon with supercar performance and family practicality.",
    long_description:
      "The Audi RS6 Avant Performance redefines the super wagon category with 621 horsepower from its 4.0L twin-turbo V8 and Quattro all-wheel drive. Accelerating from 0-100 km/h in 3.4 seconds with massive 850 Nm torque, it seats five with 1,513 liters of cargo space. Audi's ultimate performance estate combines track capability, luxury, and everyday usability in one package.",
    features: [
      "4.0L twin-turbo V8 mild-hybrid",
      "8-speed Tiptronic transmission",
      "Quattro all-wheel drive",
      "RS adaptive air suspension",
      "Active roll stabilization",
      "22-inch RS forged wheels",
      "Carbon-ceramic brakes option",
      "RS sport exhaust system",
      "12.3-inch Virtual Cockpit Plus",
      "Bang & Olufsen Advanced 3D sound",
    ],
    highlights: [
      "621 HP twin-turbo V8",
      "3.4s 0-100 km/h acceleration",
      "850 Nm torque",
      "1,513L max cargo capacity",
      "280 km/h top speed option",
    ],
    why_choose: [
      "Supercar performance with wagon practicality",
      "Seats 5 adults comfortably",
      "Best-in-class towing capacity",
      "Luxury interior rivals sedans",
      "Excellent for Dubai's highways and dunes",
    ],
    specs: {
      passengers: 5,
      luggage: 4,
      transmission: "8-speed Automatic",
      doors: 5,
      engine: "4.0L V8 Twin-Turbo",
      fuel_type: "Petrol",
      horsepower: "621 HP",
      acceleration: "3.4s 0-100 km/h",
      top_speed: "280 km/h",
      drive_type: "AWD",
    },
    has_chauffeur: false,
  },
  {
    slug: "mercedes-amg-gt-63",
    display_name: "Mercedes-AMG GT 63 S 4MATIC+",
    brand: "Mercedes-Benz",
    model: "AMG GT",
    variant: "63 S 4-Door Coupe",
    model_year: 2024,
    category: "Luxury",
    tags: ["sedan", "performance", "luxury", "amg"],
    location_default: "Dubai",
    main_image: "string",
    gallery_images: ["string"],
    thumbnail: null,
    description:
      "630 HP twin-turbo V8 four-door supercar blending GT styling with explosive performance.",
    long_description:
      "The Mercedes-AMG GT 63 S 4MATIC+ delivers 630 horsepower through its hand-built 4.0L twin-turbo V8 and 4MATIC+ all-wheel drive. Achieving 0-100 km/h in 3.2 seconds with a 315 km/h top speed, this four-door GT offers supercar dynamics while seating four adults comfortably. Advanced aerodynamics, adaptive suspension, and Drift Mode create a uniquely thrilling driving experience.",
    features: [
      "Hand-built 4.0L V8 biturbo + EQ Boost",
      "9-speed AMG Speedshift MCT",
      "AMG Performance 4MATIC+ AWD",
      "Adaptive air suspension",
      "Rear-axle steering",
      "Carbon-ceramic brakes option",
      "21-inch AMG forged wheels",
      "Burmester High-End 3D audio",
      "12.3-inch dual MBUX displays",
      "Active ambient lighting",
    ],
    highlights: [
      "630 HP twin-turbo V8",
      "3.2s 0-100 km/h acceleration",
      "900 Nm torque",
      "315 km/h top speed",
      "Drift Mode capability",
    ],
    why_choose: [
      "Supercar performance with four seats",
      "Sleekest four-door performance car",
      "AMG hand-built engine prestige",
      "Versatile for daily use and track days",
      "Dominates Dubai's luxury scene",
    ],
    specs: {
      passengers: 4,
      luggage: 3,
      transmission: "9-speed Automatic",
      doors: 4,
      engine: "4.0L V8 Twin-Turbo",
      fuel_type: "Petrol",
      horsepower: "630 HP",
      acceleration: "3.2s 0-100 km/h",
      top_speed: "315 km/h",
      drive_type: "AWD",
    },
    has_chauffeur: false,
  },
  {
    slug: "bmw-m5-competition",
    display_name: "BMW M5 Competition",
    brand: "BMW",
    model: "M5",
    variant: "Competition",
    model_year: 2026,
    category: "Luxury",
    tags: ["sedan", "performance", "luxury", "hybrid"],
    location_default: "Dubai",
    main_image: "string",
    gallery_images: ["string"],
    thumbnail: null,
    description:
      "717 HP plug-in hybrid M5 with V8 power and electric torque for supercar performance.",
    long_description:
      "The 2026 BMW M5 Competition introduces M Hybrid technology combining a twin-turbo 4.4L V8 with electric motor for 717 total horsepower and 1,000 Nm torque. Accelerating from 0-100 km/h in 3.5 seconds, this plug-in hybrid super sedan offers up to 35km electric range while delivering track-capable dynamics. BMW's most powerful M5 ever redefines performance sedan benchmarks.",
    features: [
      "M Hybrid V8 powertrain (717 HP combined)",
      "8-speed M Steptronic Sport transmission",
      "M xDrive all-wheel drive",
      "Active M differential",
      "Adaptive M suspension Professional",
      "Carbon-ceramic brakes option",
      "21-inch M alloy wheels",
      "M Carbon exterior package available",
      "12.3-inch curved M display",
      "Harman Kardon surround sound",
    ],
    highlights: [
      "717 HP total system output",
      "3.5s 0-100 km/h acceleration",
      "1,000 Nm maximum torque",
      "305 km/h top speed",
      "35km electric-only range",
    ],
    why_choose: [
      "Supercar power with sedan practicality",
      "Plug-in hybrid efficiency",
      "Track-capable with daily comfort",
      "Advanced M xDrive traction",
      "Ultimate executive performance",
    ],
    specs: {
      passengers: 5,
      luggage: 3,
      transmission: "8-speed Automatic",
      doors: 4,
      engine: "4.4L V8 Twin-Turbo + Electric Motor",
      fuel_type: "Petrol Hybrid",
      horsepower: "717 HP",
      acceleration: "3.5s 0-100 km/h",
      top_speed: "305 km/h",
      drive_type: "AWD",
    },
    has_chauffeur: false,
  },
  {
    slug: "bmw-m4-competition",
    display_name: "BMW M4 Competition xDrive",
    brand: "BMW",
    model: "M4",
    variant: "Competition xDrive",
    model_year: 2026,
    category: "Sports",
    tags: ["coupe", "performance", "m-car", "luxury"],
    location_default: "Dubai",
    main_image: "string",
    gallery_images: ["string"],
    thumbnail: null,
    description:
      "523 HP twin-turbo inline-six sports coupe with M xDrive all-wheel drive precision.",
    long_description:
      "The BMW M4 Competition xDrive delivers 523 horsepower from its hand-assembled S58 3.0L twin-turbo inline-six engine through M xDrive all-wheel drive with rear bias. Achieving 0-100 km/h in 3.5 seconds, it combines track-honed dynamics with daily usability. Aggressive styling, advanced chassis technology, and M Performance parts create the ultimate driver's coupe.",
    features: [
      "S58 3.0L twin-turbo inline-six",
      "8-speed M Steptronic transmission",
      "M xDrive AWD with drift mode",
      "Adaptive M suspension",
      "M Carbon ceramic brakes option",
      "19/20-inch M forged wheels",
      "M Sport differential",
      "Laser LED headlights",
      "12.3-inch curved M display",
      "Harman Kardon audio",
    ],
    highlights: [
      "523 HP @ 6250 rpm",
      "650 Nm torque @ 2750 rpm",
      "3.5s 0-100 km/h acceleration",
      "290 km/h top speed (optional)",
      "440L trunk capacity",
    ],
    why_choose: [
      "Inline-six character with supercar power",
      "M xDrive traction without losing fun",
      "Perfect track-and-street balance",
      "Timeless coupe proportions",
      "Strong Dubai rental demand",
    ],
    specs: {
      passengers: 4,
      luggage: 2,
      transmission: "8-speed Automatic",
      doors: 2,
      engine: "3.0L Inline-6 Twin-Turbo",
      fuel_type: "Petrol",
      horsepower: "523 HP",
      acceleration: "3.5s 0-100 km/h",
      top_speed: "290 km/h",
      drive_type: "AWD",
    },
    has_chauffeur: false,
  },
  {
    slug: "porsche-718-boxster",
    display_name: "Porsche 718 Boxster",
    brand: "Porsche",
    model: "718 Boxster",
    variant: "GTS 4.0",
    model_year: 2026,
    category: "Convertible",
    tags: ["convertible", "sports car", "luxury", "performance"],
    location_default: "Dubai",
    main_image: "string",
    gallery_images: ["string"],
    thumbnail: null,
    description:
      "Mid-engine roadster blending razor-sharp handling with pure open-top Porsche driving.",
    long_description:
      "The Porsche 718 Boxster GTS 4.0 features a naturally aspirated 4.0L flat-six engine producing 394 horsepower with the signature Porsche boxer soundtrack. Achieving 0-100 km/h in 4.3 seconds through a lightning-fast PDK transmission, it offers perfect 50:50 weight distribution and PASM suspension tuning. Porsche's entry-level sports car delivers 911-level dynamics in a more accessible, roof-down package.",
    features: [
      "4.0L naturally aspirated flat-six",
      "6-speed manual or 7-speed PDK",
      "Porsche Active Suspension Management",
      "Porsche Torque Vectoring chassis",
      "20-inch Carrera S wheels",
      "Sports Chrono package",
      "Electric soft top (10s operation)",
      "10.9-inch PCM touchscreen",
      "BOSE surround sound option",
      "Matrix LED headlights",
    ],
    highlights: [
      "394 HP naturally aspirated flat-six",
      "4.3s 0-100 km/h acceleration",
      "293 km/h top speed",
      "Mid-engine balance perfection",
    ],
    why_choose: [
      "Purest Porsche driving experience",
      "Flat-six character and sound",
      "Accessible Porsche performance",
      "Perfect for Dubai coastal drives",
      "Excellent value retention",
    ],
    specs: {
      passengers: 2,
      luggage: 1,
      transmission: "7-speed PDK Automatic",
      doors: 2,
      engine: "4.0L Flat-6 Naturally Aspirated",
      fuel_type: "Petrol",
      horsepower: "394 HP",
      acceleration: "4.3s 0-100 km/h",
      top_speed: "293 km/h",
      drive_type: "RWD",
    },
    has_chauffeur: false,
  },
  {
    slug: "porsche-718-boxster-style-edition",
    display_name: "Porsche 718 Boxster Style Edition",
    brand: "Porsche",
    model: "718 Boxster",
    variant: "Style Edition (Black)",
    model_year: 2026,
    category: "Convertible",
    tags: ["convertible", "sports car", "special edition", "black edition"],
    location_default: "Dubai",
    main_image: "string",
    gallery_images: ["string"],
    thumbnail: null,
    description:
      "Limited-edition 718 Boxster with exclusive black styling and enhanced standard equipment.",
    long_description:
      "The Porsche 718 Boxster Style Edition (Black package) features exclusive high-gloss black 20-inch 718 Spyder wheels, black sport tailpipes, and PORSCHE lettering in silver. The black contrast package adds hood stripes, side logos, and coordinated black accents throughout. Powered by the 300 hp 2.0L turbo flat-four, it combines signature mid-engine balance with distinctive Style Edition styling perfect for Dubai's luxury scene.",
    features: [
      "20-inch 718 Spyder wheels (high-gloss black)",
      "Black Sport Tailpipes",
      "Black contrast package (hood stripes, side logos)",
      "Boxster script embossed on convertible top",
      "Black leather interior with Chalk stitching",
      "Heated multifunction steering wheel",
      "Porsche crests on wheel hubs",
      "LED Matrix headlights",
      "BOSE audio system option",
      "7-speed PDK or 6-speed manual",
    ],
    highlights: [
      "300 HP turbocharged flat-four",
      "4.9s 0-100 km/h acceleration",
      "275 km/h top speed",
      "Exclusive Style Edition badging",
    ],
    why_choose: [
      "Distinctive blacked-out styling",
      "Generous standard equipment",
      "Perfect entry to Porsche ownership",
      "Mid-engine purity with open-top freedom",
      "High demand in collectors market",
    ],
    specs: {
      passengers: 2,
      luggage: 1,
      transmission: "6-speed Manual",
      doors: 2,
      engine: "2.0L Flat-4 Turbocharged",
      fuel_type: "Petrol",
      horsepower: "300 HP",
      acceleration: "4.9s 0-100 km/h",
      top_speed: "275 km/h",
      drive_type: "RWD",
    },
    has_chauffeur: false,
  },
  {
    slug: "porsche-718-boxster-style-edition-white",
    display_name: "Porsche 718 Boxster Style Edition (White)",
    brand: "Porsche",
    model: "718 Boxster",
    variant: "Style Edition White",
    model_year: 2026,
    category: "Convertible",
    tags: ["convertible", "sports car", "special edition", "white edition"],
    location_default: "Dubai",
    main_image: "string",
    gallery_images: ["string"],
    thumbnail: null,
    description:
      "Limited-edition 718 Boxster with striking white contrast package and premium appointments.",
    long_description:
      "The Porsche 718 Boxster Style Edition in white features the exclusive White Contrast Package with high-gloss white 20-inch wheels, white sport tailpipes, hood stripes, and PORSCHE lettering. Carrara White Metallic exterior pairs with black leather interior and Chalk contrast stitching for sophisticated style. The 300 hp 2.0L turbocharged flat-four maintains pure mid-engine dynamics perfect for Dubai's coastal drives.",
    features: [
      "20-inch wheels in high-gloss white",
      "White Sport Tailpipes",
      "White Contrast Package (hood stripes, logos)",
      "Boxster script on convertible top",
      "Black leather with Chalk stitching",
      "Porsche crests on white wheel centers",
      "LED Matrix headlights in black",
      "Heated GT sport steering wheel",
      "Storage package with luggage nets",
      "6-speed manual transmission",
    ],
    highlights: [
      "300 HP turbo flat-four engine",
      "4.9s 0-100 km/h acceleration",
      "275 km/h top speed",
      "Exclusive Style Edition styling",
    ],
    why_choose: [
      "Clean white-on-black aesthetic",
      "Generous factory options included",
      "Perfect Porsche entry point",
      "Mid-engine balance mastery",
      "High resale value potential",
    ],
    specs: {
      passengers: 2,
      luggage: 1,
      transmission: "6-speed Manual",
      doors: 2,
      engine: "2.0L Flat-4 Turbocharged",
      fuel_type: "Petrol",
      horsepower: "300 HP",
      acceleration: "4.9s 0-100 km/h",
      top_speed: "275 km/h",
      drive_type: "RWD",
    },
    has_chauffeur: false,
  },
  {
    slug: "bmw-420i",
    display_name: "BMW 420i Coupe",
    brand: "BMW",
    model: "4 Series",
    variant: "420i",
    model_year: 2026,
    category: "Luxury",
    tags: ["coupe", "luxury", "sporty"],
    location_default: "Dubai",
    main_image: "string",
    gallery_images: ["string"],
    thumbnail: null,
    description:
      "Premium compact coupe with sporty dynamics and efficient turbocharged performance.",
    long_description:
      "The BMW 420i Coupe offers refined driving dynamics powered by a 2.0L turbocharged inline-four engine producing 184 horsepower. With rear-wheel drive, precise steering, and BMW's signature handling, it provides engaging performance for daily driving. Luxurious interior, advanced driver aids, and sleek coupe styling make it ideal for urban sophistication in Dubai.",
    features: [
      "2.0L BMW TwinPower Turbo 4-cylinder",
      "8-speed automatic transmission",
      "Dynamic Stability Control",
      "iDrive 8.5 infotainment system",
      "12.3-inch digital instrument cluster",
      "14.9-inch central touchscreen",
      "LED headlights with cornering lights",
      "Heated front seats",
      "Wireless Apple CarPlay/Android Auto",
      "Parking assistant with rear camera",
    ],
    highlights: [
      "184 HP with 300 Nm torque",
      "7.3s 0-100 km/h acceleration",
      "235 km/h top speed",
      "5.8 L/100km combined efficiency",
    ],
    why_choose: [
      "Perfect balance of performance and economy",
      "BMW driving dynamics in accessible package",
      "Premium coupe styling",
      "Comprehensive standard equipment",
      "Excellent for Dubai city driving",
    ],
    specs: {
      passengers: 4,
      luggage: 2,
      transmission: "8-speed Automatic",
      doors: 2,
      engine: "2.0L Inline-4 Turbocharged",
      fuel_type: "Petrol",
      horsepower: "184 HP",
      acceleration: "7.3s 0-100 km/h",
      top_speed: "235 km/h",
      drive_type: "RWD",
    },
    has_chauffeur: false,
  },
  {
    slug: "bmw-420i-grey",
    display_name: "BMW 420i Coupe (Brooklyn Grey)",
    brand: "BMW",
    model: "4 Series",
    variant: "420i M Sport",
    model_year: 2026,
    category: "Luxury",
    tags: ["coupe", "luxury", "sporty", "grey"],
    location_default: "Dubai",
    main_image: "string",
    gallery_images: ["string"],
    thumbnail: null,
    description:
      "Elegant BMW 420i Coupe in sophisticated Brooklyn Grey metallic paint.",
    long_description:
      "The BMW 420i Coupe in Brooklyn Grey Metallic combines premium coupe styling with the refined performance of BMW's 2.0L turbocharged inline-four engine. This popular grey shade offers a subtle yet sophisticated appearance that complements the car's athletic proportions. M Sport package enhances the sporty character with unique styling elements and dynamic chassis tuning perfect for Dubai's urban luxury scene.",
    features: [
      "Brooklyn Grey Metallic paint",
      "M Sport aerodynamic package",
      "M Sport suspension",
      "18-inch M double-spoke wheels",
      "Vernasca leather upholstery",
      "Anthracite headliner",
      "M Sport leather steering wheel",
      "LED headlights with signature DRL",
      "iDrive 8.5 with curved display",
      "Wireless charging and Apple CarPlay",
    ],
    highlights: [
      "184 HP turbocharged 2.0L engine",
      "7.3s 0-100 km/h acceleration",
      "Premium Brooklyn Grey paint",
      "M Sport performance upgrades",
      "Luxury coupe practicality",
    ],
    why_choose: [
      "Sophisticated Brooklyn Grey complements coupe lines",
      "M Sport styling without M performance pricing",
      "Ideal color for Dubai's luxury market",
      "Balanced performance for daily driving",
      "High resale value retention",
    ],
    specs: {
      passengers: 4,
      luggage: 2,
      transmission: "8-speed Automatic",
      doors: 2,
      engine: "2.0L Inline-4 Turbocharged",
      fuel_type: "Petrol",
      horsepower: "184 HP",
      acceleration: "7.3s 0-100 km/h",
      top_speed: "235 km/h",
      drive_type: "RWD",
    },
    has_chauffeur: false,
  },
  {
    slug: "porsche-panamera",
    display_name: "Porsche Panamera 4 E-Hybrid",
    brand: "Porsche",
    model: "Panamera",
    variant: "4 E-Hybrid",
    model_year: 2026,
    category: "Luxury",
    tags: ["sedan", "luxury", "hybrid", "performance"],
    location_default: "Dubai",
    main_image: "string",
    gallery_images: ["string"],
    thumbnail: null,
    description:
      "Porsche's four-door sports car blending supercar performance with luxury sedan practicality.",
    long_description:
      "The 2026 Porsche Panamera 4 E-Hybrid combines a 2.9L twin-turbo V6 with electric motor for 463 total horsepower and up to 50km electric range. Achieving 0-100 km/h in 4.1 seconds, it offers Porsche Active Suspension Management, rear-axle steering, and seating for four with generous luggage space. Perfect balance of executive luxury and sports car dynamics for Dubai's demanding drivers.",
    features: [
      "2.9L V6 twin-turbo + electric motor",
      "8-speed PDK dual-clutch transmission",
      "Porsche Traction Management AWD",
      "PASM adaptive air suspension",
      "Rear-axle steering",
      "21-inch Panamera Turbo wheels",
      "Porsche InnoDrive adaptive cruise",
      "HD-Matrix LED headlights",
      "14.1-inch curved driver display",
      "Bose surround sound system",
    ],
    highlights: [
      "463 HP total system power",
      "4.1s 0-100 km/h acceleration",
      "50km electric-only range",
      "298 km/h top speed",
      "4 seats + 495L cargo",
    ],
    why_choose: [
      "Only four-door Porsche sports car",
      "Plug-in hybrid efficiency",
      "Supercar performance with sedan space",
      "Rear-axle steering agility",
      "Ultimate executive transport",
    ],
    specs: {
      passengers: 4,
      luggage: 3,
      transmission: "8-speed PDK Automatic",
      doors: 4,
      engine: "2.9L V6 Twin-Turbo + Hybrid",
      fuel_type: "Petrol Hybrid",
      horsepower: "463 HP",
      acceleration: "4.1s 0-100 km/h",
      top_speed: "298 km/h",
      drive_type: "AWD",
    },
    has_chauffeur: false,
  },
  {
    slug: "jeep-wrangler",
    display_name: "Jeep Wrangler Rubicon",
    brand: "Jeep",
    model: "Wrangler",
    variant: "Rubicon",
    model_year: 2026,
    category: "SUV",
    tags: ["suv", "offroad", "4x4", "adventure"],
    location_default: "Dubai",
    main_image: "string",
    gallery_images: ["string"],
    thumbnail: null,
    description:
      "Iconic off-road legend with unmatched trail capability and removable doors/roof.",
    long_description:
      "The Jeep Wrangler Rubicon represents the pinnacle of off-road capability with Rock-Trac 4x4, 44-degree approach angle, 37-inch off-road tires, and 12.9 inches of ground clearance. Powered by a 2.0L turbo Hurricane engine producing 270 HP, it conquers Rubicon Trail rocks while offering modern tech like Uconnect 5. Removable doors, roof, and windshield create the ultimate open-air adventure vehicle perfect for Dubai desert expeditions.",
    features: [
      "Rock-Trac 4x4 with 4:1 low range",
      "Electronic front sway-bar disconnect",
      "Tru-Lok locking differentials",
      "Fox 2.0 shocks with bypass",
      "Removable doors and roof panels",
      "12.9-inch ground clearance",
      "37-inch off-road tires",
      "12.3-inch Uconnect 5 touchscreen",
      "Forward-facing camera",
      "Water fording 34 inches",
    ],
    highlights: [
      "270 HP 2.0L turbo Hurricane engine",
      "77.4:1 crawl ratio",
      "44° approach/37° departure angles",
      "12.9-inch ground clearance",
      "3,500 lbs towing capacity",
    ],
    why_choose: [
      "Most capable production off-roader",
      "Authentic Jeep heritage design",
      "Ultimate Dubai desert adventure vehicle",
      "Removable components for open-air freedom",
      "Strong resale value worldwide",
    ],
    specs: {
      passengers: 5,
      luggage: 3,
      transmission: "8-speed Automatic",
      doors: 4,
      engine: "2.0L Turbo 4-Cylinder",
      fuel_type: "Petrol",
      horsepower: "270 HP",
      acceleration: "7.5s 0-100 km/h",
      top_speed: "180 km/h",
      drive_type: "4WD",
    },
    has_chauffeur: false,
  },
  {
    slug: "lamborghini-revuelto",
    display_name: "Lamborghini Revuelto",
    brand: "Lamborghini",
    model: "Revuelto",
    variant: "LP 1015-4",
    model_year: 2026,
    category: "Supercar",
    tags: ["supercar", "hybrid", "v12", "high-performance"],
    location_default: "Dubai",
    main_image: "string",
    gallery_images: ["string"],
    thumbnail: null,
    description:
      "Lamborghini's first hybrid supercar with 1,001+ HP V12 power replacing the Aventador.",
    long_description:
      "The Lamborghini Revuelto combines a naturally aspirated 6.5L V12 with three electric motors for over 1,001 horsepower and electrified AWD. Achieving 0-100 km/h in 2.5 seconds with >350 km/h top speed, it features active aerodynamics, rear-wheel steering, and an 8-speed dual-clutch transmission. Lamborghini's HPEV (High Performance Electrified Vehicle) delivers Aventador evolution with hybrid technology and scissor doors.",
    features: [
      "6.5L naturally aspirated V12 + 3 e-motors",
      "8-speed dual-clutch automatic",
      "Electrified all-wheel drive",
      "Active aerodynamics (ALA 2.0)",
      "Rear-wheel steering",
      "Carbon-ceramic brakes",
      "20/21-inch forged wheels",
      "Central touchscreen + digital cluster",
      "LiDAR-assisted driving modes",
      "Scissor doors",
    ],
    highlights: [
      "1,001+ HP total system output",
      "2.5s 0-100 km/h acceleration",
      ">350 km/h top speed",
      "6.5L V12 revs to 10,000+ rpm",
    ],
    why_choose: [
      "Most powerful Lamborghini V12 ever",
      "Hybrid technology doubles downforce",
      "Final evolution of scissor-door supercars",
      "Track-capable with street compliance",
      "Ultimate Dubai supercar status",
    ],
    specs: {
      passengers: 2,
      luggage: 1,
      transmission: "8-speed Dual-Clutch Automatic",
      doors: 2,
      engine: "6.5L V12 Naturally Aspirated + Hybrid",
      fuel_type: "Petrol Hybrid",
      horsepower: "1001 HP",
      acceleration: "2.5s 0-100 km/h",
      top_speed: "350 km/h",
      drive_type: "AWD",
    },
    has_chauffeur: false,
  },
  {
    slug: "porsche-718-cayman-gt4",
    display_name: "Porsche 718 Cayman GT4",
    brand: "Porsche",
    model: "718 Cayman",
    variant: "GT4",
    model_year: 2026,
    category: "Sports",
    tags: ["coupe", "track", "performance", "gt"],
    location_default: "Dubai",
    main_image: "string",
    gallery_images: ["string"],
    thumbnail: null,
    description:
      "Track-focused mid-engine coupe with GT3-derived 4.0L flat-six and aerodynamic mastery.",
    long_description:
      "The Porsche 718 Cayman GT4 features a naturally aspirated 4.0-liter flat-six engine producing 414 horsepower, borrowed from the 911 GT3. With a 6-speed manual or 7-speed PDK transmission, it achieves 0-100 km/h in 4.4 seconds and generates 122 kg of downforce at top speed. Massive aerodynamic upgrades, track-tuned suspension, and carbon fiber components create a pure driver's car that rivals dedicated track machines while remaining street-legal.",
    features: [
      "4.0L naturally aspirated flat-six (GT3-derived)",
      "6-speed GT manual or 7-speed PDK",
      "Porsche Active Suspension Management",
      "Large rear wing + front splitter",
      "20-inch center-lock wheels",
      "Carbon fiber reinforced hood",
      "Porsche Torque Vectoring Plus",
      "Alcantara interior",
      "Sports Chrono package",
      "Lift system option",
    ],
    highlights: [
      "414 HP @ 7600 rpm",
      "4.4s 0-100 km/h acceleration",
      "304 km/h top speed",
      "122 kg aerodynamic downforce",
      "8000 rpm redline",
    ],
    why_choose: [
      "911 GT3 engine in Cayman chassis",
      "Perfect 50:50 weight distribution",
      "Track weapon with road compliance",
      "Naturally aspirated flat-six soundtrack",
      "Limited production collector appeal",
    ],
    specs: {
      passengers: 2,
      luggage: 1,
      transmission: "6-speed Manual",
      doors: 2,
      engine: "4.0L Flat-6 Naturally Aspirated",
      fuel_type: "Petrol",
      horsepower: "414 HP",
      acceleration: "4.4s 0-100 km/h",
      top_speed: "304 km/h",
      drive_type: "RWD",
    },
    has_chauffeur: false,
  },
  {
    slug: "audi-rs-q8-performance",
    display_name: "Audi RS Q8 Performance",
    brand: "Audi",
    model: "RS Q8",
    variant: "Performance",
    model_year: 2026,
    category: "SUV",
    tags: ["suv", "performance", "luxury", "v8"],
    location_default: "Dubai",
    main_image: "string",
    gallery_images: ["string"],
    thumbnail: null,
    description:
      "631 HP twin-turbo V8 super SUV with Nürburgring record and supercar performance.",
    long_description:
      "The 2026 Audi RS Q8 Performance boasts a 4.0L twin-turbo V8 producing 631 horsepower and 850 Nm torque, achieving 0-100 km/h in 3.6 seconds. Quattro AWD with electromechanical active roll stabilization and 23-inch wheels deliver track-capable dynamics in a 5-seat luxury package. Audi's fastest production SUV sets new benchmarks for performance family transport.",
    features: [
      "4.0L twin-turbo V8 mild-hybrid",
      "8-speed Tiptronic transmission",
      "Quattro AWD with sport differential",
      "Electromechanical active roll control",
      "RS adaptive air suspension",
      "23-inch forged wheels",
      "Carbon-ceramic brakes option",
      "RS sport exhaust with valves",
      "12.3-inch Virtual Cockpit Plus",
      "Bang & Olufsen Advanced 3D sound",
    ],
    highlights: [
      "631 HP twin-turbo V8",
      "3.6s 0-100 km/h acceleration",
      "850 Nm torque",
      "305 km/h top speed option",
      "Nürburgring lap record holder",
    ],
    why_choose: [
      "Supercar power with 5 seats",
      "Fastest Audi SUV ever produced",
      "Track-capable family hauler",
      "Luxury rivals Bentley interior",
      "Perfect Dubai supercar alternative",
    ],
    specs: {
      passengers: 5,
      luggage: 4,
      transmission: "8-speed Automatic",
      doors: 5,
      engine: "4.0L V8 Twin-Turbo",
      fuel_type: "Petrol",
      horsepower: "631 HP",
      acceleration: "3.6s 0-100 km/h",
      top_speed: "305 km/h",
      drive_type: "AWD",
    },
    has_chauffeur: false,
  },
  {
    slug: "rolls-royce-phantom",
    display_name: "Rolls-Royce Phantom VIII",
    brand: "Rolls-Royce",
    model: "Phantom",
    variant: "Extended Wheelbase",
    model_year: 2026,
    category: "Luxury",
    tags: ["sedan", "luxury", "bespoke", "v12"],
    location_default: "Dubai",
    main_image: "string",
    gallery_images: ["string"],
    thumbnail: null,
    description:
      "Ultimate expression of automotive luxury with hand-built V12 and limitless customization.",
    long_description:
      "The Rolls-Royce Phantom VIII features a hand-assembled 6.75L twin-turbo V12 producing 563 hp and 900 Nm torque, mated to an 8-speed automatic with rear-wheel drive. Measuring 5,982 mm long with a 3,772 mm wheelbase, it offers unmatched rear passenger space and serenity through Planar Suspension and Flagbearer road-scanning technology. Every Phantom receives 450+ hours of hand craftsmanship with bespoke Gallery artwork and Starlight Headliner.",
    features: [
      "Hand-built 6.75L twin-turbo V12",
      "8-speed automatic transmission",
      "Planar Suspension system",
      "Rear-hinged coach doors",
      "Starlight Headliner (1,500+ fiber optics)",
      "Gallery interpretation display",
      "Electronic 'Magic Carpet' ride",
      "Rear Privacy Suite option",
      "Bespoke audio system",
      "Hand-polished Pantheon grille",
    ],
    highlights: [
      "563 HP twin-turbocharged V12",
      "5.1s 0-100 km/h acceleration",
      "900 Nm torque from 1,700 rpm",
      "250 km/h electronically limited",
      "5,982 mm length (EWB)",
    ],
    why_choose: [
      "Pinnacle of automotive luxury",
      "Unmatched rear-seat accommodations",
      "Limitless bespoke personalization",
      "Landmark presence everywhere",
      "Ultimate status symbol",
    ],
    specs: {
      passengers: 5,
      luggage: 3,
      transmission: "8-speed Automatic",
      doors: 4,
      engine: "6.75L V12 Twin-Turbo",
      fuel_type: "Petrol",
      horsepower: "563 HP",
      acceleration: "5.1s 0-100 km/h",
      top_speed: "250 km/h",
      drive_type: "RWD",
    },
    has_chauffeur: true,
  },
  {
    slug: "audi-q8",
    display_name: "Audi Q8 55 TFSI",
    brand: "Audi",
    model: "Q8",
    variant: "55 TFSI quattro",
    model_year: 2026,
    category: "SUV",
    tags: ["suv", "luxury", "performance"],
    location_default: "Dubai",
    main_image: "string",
    gallery_images: ["string"],
    thumbnail: null,
    description:
      "Premium large SUV combining coupe styling with Q7 practicality and V6 performance.",
    long_description:
      "The Audi Q8 features a 3.0L turbocharged V6 mild-hybrid engine producing 335 horsepower and 500 Nm torque through Quattro all-wheel drive and 8-speed Tiptronic transmission. With 605 liters of cargo space and seating for five, it blends athletic coupe proportions with family versatility. Advanced Matrix LED headlights, Virtual Cockpit, and MMI touchscreens create a premium digital cockpit.",
    features: [
      "3.0L V6 turbocharged mild-hybrid",
      "8-speed Tiptronic automatic",
      "Quattro all-wheel drive",
      "Adaptive air suspension",
      "Matrix LED headlights",
      "12.3-inch Virtual Cockpit",
      "10.1-inch MMI touchscreen",
      "Bang & Olufsen sound system",
      "Wireless Apple CarPlay/Android Auto",
      "360-degree camera system",
    ],
    highlights: [
      "335 HP V6 turbo engine",
      "5.6s 0-100 km/h acceleration",
      "500 Nm torque",
      "250 km/h top speed",
      "605L cargo capacity",
    ],
    why_choose: [
      "Coupe SUV styling with SUV space",
      "Refined V6 performance",
      "Premium Audi interior quality",
      "Excellent highway cruiser",
      "Strong Dubai luxury demand",
    ],
    specs: {
      passengers: 5,
      luggage: 4,
      transmission: "8-speed Automatic",
      doors: 5,
      engine: "3.0L V6 Turbocharged",
      fuel_type: "Petrol",
      horsepower: "335 HP",
      acceleration: "5.6s 0-100 km/h",
      top_speed: "250 km/h",
      drive_type: "AWD",
    },
    has_chauffeur: false,
  },
  {
    slug: "cadillac-escalade-sport",
    display_name: "Cadillac Escalade Sport",
    brand: "Cadillac",
    model: "Escalade",
    variant: "Sport",
    model_year: 2026,
    category: "7Seater",
    tags: ["suv", "luxury", "v8", "towing"],
    location_default: "Dubai",
    main_image: "string",
    gallery_images: ["string"],
    thumbnail: null,
    description:
      "Flagship American luxury SUV with powerful V8, massive towing capacity, and bold Sport styling.",
    long_description:
      "The Cadillac Escalade Sport features a 6.2L V8 engine producing 420 horsepower and 460 lb-ft torque through a 10-speed automatic transmission. Measuring 211.9 inches long with seating for seven plus 25.5 cu.ft. cargo (121 cu.ft. max), it offers 8,100 lbs towing capacity. Sport trim adds gloss black accents, unique grille, and 22-inch dark Android wheels for aggressive luxury presence.",
    features: [
      "6.2L EcoTec3 V8 engine",
      "10-speed automatic transmission",
      "Magnetic Ride Control suspension",
      "22-inch Sport alloy wheels",
      "Gloss Black grille and accents",
      "19-speaker AKG Studio audio",
      "38-speaker AKG Studio Reference",
      "55-inch diagonal OLED display",
      "Super Cruise hands-free driving",
      "Night vision camera",
    ],
    highlights: [
      "420 HP 6.2L V8 engine",
      "8,100 lbs maximum towing",
      "121 cu.ft. maximum cargo",
      "55-inch OLED infotainment",
      "7-passenger luxury seating",
    ],
    why_choose: [
      "Ultimate American luxury SUV",
      "Massive towing and payload",
      "Bold Sport exterior styling",
      "Advanced Super Cruise tech",
      "Statement vehicle everywhere",
    ],
    specs: {
      passengers: 7,
      luggage: 4,
      transmission: "10-speed Automatic",
      doors: 5,
      engine: "6.2L V8",
      fuel_type: "Petrol",
      horsepower: "420 HP",
      acceleration: "6.0s 0-100 km/h",
      top_speed: "130 mph",
      drive_type: "RWD",
    },
    has_chauffeur: false,
  },
  {
    slug: "bmw-735i",
    display_name: "BMW 735i M Sport",
    brand: "BMW",
    model: "7 Series",
    variant: "735i",
    model_year: 2026,
    category: "Luxury",
    tags: ["sedan", "luxury", "executive"],
    location_default: "Dubai",
    main_image: "string",
    gallery_images: ["string"],
    thumbnail: null,
    description:
      "Entry-level BMW 7 Series with smooth inline-six power and M Sport luxury styling.",
    long_description:
      "The BMW 735i features a 3.0L turbocharged inline-six engine producing 272 horsepower and 425 Nm torque through an 8-speed automatic transmission. Measuring 5,395 mm long, it offers exceptional rear legroom, advanced driver assistance systems, and the largest curved display in its class. M Sport package adds athletic styling with 20-inch wheels and adaptive suspension for refined grand touring.",
    features: [
      "3.0L BMW TwinPower Turbo inline-six",
      "8-speed Steptronic automatic",
      "xDrive all-wheel drive option",
      "M Sport adaptive suspension",
      "20-inch M alloy wheels",
      "Curved Display (14.9-inch + 12.3-inch)",
      "BMW iDrive 8.5 with QuickSelect",
      "Harman Kardon surround sound",
      "Panoramic glass sunroof",
      "Executive Lounge rear seating",
    ],
    highlights: [
      "272 HP turbocharged inline-six",
      "6.4s 0-100 km/h acceleration",
      "425 Nm torque",
      "250 km/h top speed",
      "520L trunk capacity",
    ],
    why_choose: [
      "Smooth inline-six refinement",
      "M Sport styling at entry price",
      "Advanced digital cockpit",
      "Excellent long-distance cruiser",
      "Premium executive presence",
    ],
    specs: {
      passengers: 5,
      luggage: 3,
      transmission: "8-speed Automatic",
      doors: 4,
      engine: "3.0L Inline-6 Turbocharged",
      fuel_type: "Petrol",
      horsepower: "272 HP",
      acceleration: "6.4s 0-100 km/h",
      top_speed: "250 km/h",
      drive_type: "RWD",
    },
    has_chauffeur: false,
  },
  {
    slug: "audi-rs4-performance",
    display_name: "Audi RS4 Avant Performance",
    brand: "Audi",
    model: "RS4",
    variant: "Performance",
    model_year: 2026,
    category: "Luxury",
    tags: ["wagon", "performance", "rs", "avant"],
    location_default: "Dubai",
    main_image: "string",
    gallery_images: ["string"],
    thumbnail: null,
    description:
      "450 HP twin-turbo V6 super wagon with Quattro AWD and massive practicality.",
    long_description:
      "The Audi RS4 Avant Performance features a 2.9L twin-turbo V6 producing 450 horsepower and 600 Nm torque through an 8-speed Tiptronic transmission and Quattro all-wheel drive. Achieving 0-100 km/h in 4.1 seconds with 250 km/h top speed (280 optional), it offers 495 liters of cargo space (1,495L folded). RS Performance upgrades include carbon-ceramic brakes, 20-inch forged wheels, and RS sport suspension for track capability in a practical wagon package.",
    features: [
      "2.9L V6 twin-turbocharged",
      "8-speed Tiptronic automatic",
      "Quattro AWD with sport differential",
      "RS adaptive air suspension",
      "Carbon-ceramic brakes",
      "20-inch RS forged wheels",
      "RS sport exhaust system",
      "Virtual Cockpit Plus",
      "Bang & Olufsen 3D sound",
      "Matrix LED headlights",
    ],
    highlights: [
      "450 HP twin-turbo V6",
      "4.1s 0-100 km/h acceleration",
      "600 Nm torque",
      "495L cargo (1,495L folded)",
      "280 km/h top speed option",
    ],
    why_choose: [
      "Supercar performance with wagon utility",
      "Quattro AWD traction mastery",
      "Track-capable family transporter",
      "RS Performance exclusivity",
      "Perfect Dubai supercar alternative",
    ],
    specs: {
      passengers: 5,
      luggage: 4,
      transmission: "8-speed Automatic",
      doors: 5,
      engine: "2.9L V6 Twin-Turbo",
      fuel_type: "Petrol",
      horsepower: "450 HP",
      acceleration: "4.1s 0-100 km/h",
      top_speed: "280 km/h",
      drive_type: "AWD",
    },
    has_chauffeur: false,
  },
  {
    slug: "bmw-840i-gran-coupe",
    display_name: "BMW 840i Gran Coupe xDrive",
    brand: "BMW",
    model: "8 Series Gran Coupe",
    variant: "840i xDrive",
    model_year: 2026,
    category: "Luxury",
    tags: ["gran-coupe", "luxury", "performance", "xdrive"],
    location_default: "Dubai",
    main_image: "string",
    gallery_images: ["string"],
    thumbnail: null,
    description:
      "335 HP inline-six luxury gran coupe with xDrive AWD and grand touring refinement.",
    long_description:
      "The BMW 840i Gran Coupe xDrive features a smooth 3.0L turbocharged inline-six producing 335 horsepower and 500 Nm torque through an 8-speed automatic and xDrive all-wheel drive. With 5 seats and 440 liters trunk capacity, it blends 8 Series coupe styling with added rear practicality. Adaptive suspension, laser headlights, and iDrive 8 create a sophisticated highway cruiser perfect for long-distance luxury travel.",
    features: [
      "3.0L BMW TwinPower Turbo inline-six",
      "8-speed Steptronic automatic",
      "xDrive intelligent all-wheel drive",
      "Adaptive M suspension",
      "20-inch M light alloy wheels",
      "BMW Laserlight headlights",
      "12.3-inch digital instrument cluster",
      "14.9-inch central Control Display",
      "Harman Kardon surround sound",
      "Panoramic glass sunroof",
    ],
    highlights: [
      "335 HP @ 5000-6500 rpm",
      "5.0s 0-100 km/h acceleration",
      "500 Nm @ 1600 rpm",
      "250 km/h top speed",
      "440L trunk capacity",
    ],
    why_choose: [
      "Inline-six smoothness and power",
      "Gran Coupe practicality",
      "xDrive all-weather confidence",
      "8 Series luxury at accessible price",
      "Perfect long-distance cruiser",
    ],
    specs: {
      passengers: 5,
      luggage: 3,
      transmission: "8-speed Automatic",
      doors: 4,
      engine: "3.0L Inline-6 Turbocharged",
      fuel_type: "Petrol",
      horsepower: "335 HP",
      acceleration: "5.0s 0-100 km/h",
      top_speed: "250 km/h",
      drive_type: "AWD",
    },
    has_chauffeur: false,
  },
  {
    slug: "rolls-royce-cullinan",
    display_name: "Rolls-Royce Cullinan Series II",
    brand: "Rolls-Royce",
    model: "Cullinan",
    variant: "Series II",
    model_year: 2026,
    category: "SUV",
    tags: ["suv", "luxury", "v12", "bespoke"],
    location_default: "Dubai",
    main_image: "string",
    gallery_images: ["string"],
    thumbnail: null,
    description:
      "Pinnacle luxury SUV with V12 power, unmatched refinement, and limitless customization.",
    long_description:
      "The Rolls-Royce Cullinan combines a hand-built 6.75L twin-turbo V12 producing 563 hp and 850 Nm torque with all-wheel drive and self-levelling air suspension. Seating five with vast luggage space, it features the Glass Partition to luggage compartment, deployable Viewing Suite picnic seats, and Starlight Headliner. Every Cullinan receives extensive bespoke craftsmanship creating the world's most exclusive SUV.",
    features: [
      "Hand-built 6.75L twin-turbo V12",
      "8-speed automatic transmission",
      "All-wheel drive with off-road capability",
      "Planar Suspension system",
      "Rear coach doors",
      "Glass Partition to luggage compartment",
      "Viewing Suite (deployable picnic seats)",
      "Starlight Headliner",
      "Bespoke Lounge Rear Seating",
      "Electronic 'Magic Carpet' ride",
    ],
    highlights: [
      "563 HP @ 5000 rpm",
      "5.2s 0-100 km/h acceleration",
      "850 Nm @ 1600 rpm",
      "250 km/h electronically limited",
      "2,700+ kg luxury mastery",
    ],
    why_choose: [
      "Ultimate luxury SUV benchmark",
      "V12 serenity with SUV versatility",
      "Unrivaled bespoke personalization",
      "Landmark presence everywhere",
      "Perfect Dubai prestige vehicle",
    ],
    specs: {
      passengers: 5,
      luggage: 4,
      transmission: "8-speed Automatic",
      doors: 5,
      engine: "6.75L V12 Twin-Turbo",
      fuel_type: "Petrol",
      horsepower: "563 HP",
      acceleration: "5.2s 0-100 km/h",
      top_speed: "250 km/h",
      drive_type: "AWD",
    },
    has_chauffeur: true,
  },
  {
    slug: "mercedes-benz-a45-s",
    display_name: "Mercedes-AMG A45 S 4MATIC+",
    brand: "Mercedes-Benz",
    model: "A-Class",
    variant: "A45 S",
    model_year: 2026,
    category: "Sports",
    tags: ["hot-hatch", "performance", "amg", "4matic"],
    location_default: "Dubai",
    main_image: "string",
    gallery_images: ["string"],
    thumbnail: null,
    description:
      "World's most powerful production 4-cylinder hot hatch with 416 HP and drift mode.",
    long_description:
      "The Mercedes-AMG A45 S features hand-built 2.0L turbo 4-cylinder producing 416 hp and 369 lb-ft through 8-speed AMG dual-clutch and 4MATIC+ all-wheel drive. Achieving 0-100 km/h in 3.9 seconds with 270 km/h top speed, it includes Race-Suspend, Drift Mode, and advanced aerodynamics. Compact 5-door practicality combines with supercar performance for ultimate hot hatch mastery.",
    features: [
      "Hand-built M139 2.0L turbo 4-cyl",
      "8-speed AMG Speedshift DCT",
      "4MATIC+ variable AWD (100% rear bias)",
      "AMG Ride Control adaptive dampers",
      "Drift Mode and Race-Suspend",
      "19/20-inch AMG forged wheels",
      "Carbon fiber aero package",
      "Burmester high-end 3D sound",
      "12.3-inch digital cockpit",
      "AMG Performance steering wheel",
    ],
    highlights: [
      "416 HP from 2.0L 4-cylinder",
      "3.9s 0-100 km/h acceleration",
      "500 Nm torque peak",
      "270 km/h top speed",
      "Nürburgring lap record holder",
    ],
    why_choose: [
      "Most powerful series 4-cylinder ever",
      "Drift-capable 4MATIC+ AWD",
      "Supercar performance in hatchback",
      "AMG hand-built engine prestige",
      "Daily drivable track weapon",
    ],
    specs: {
      passengers: 5,
      luggage: 3,
      transmission: "8-speed Dual-Clutch",
      doors: 5,
      engine: "2.0L Turbocharged I4",
      fuel_type: "Petrol",
      horsepower: "416 HP",
      acceleration: "3.9s 0-100 km/h",
      top_speed: "270 km/h",
      drive_type: "AWD",
    },
    has_chauffeur: false,
  },
  {
    slug: "bmw-z4-m40i",
    display_name: "BMW Z4 M40i",
    brand: "BMW",
    model: "Z4",
    variant: "M40i",
    model_year: "2026",
    category: "Convertible",
    tags: ["roadster", "convertible", "performance", "m-performance"],
    location_default: "Dubai",
    main_image: "string",
    gallery_images: ["string"],
    thumbnail: null,
    description:
      "382 HP inline-six roadster with precise handling and pure open-top driving pleasure.",
    long_description:
      "The BMW Z4 M40i features a 3.0L twin-turbo inline-six producing 382 horsepower and 369 lb-ft torque through an 8-speed automatic and rear-wheel drive. Achieving 0-100 km/h in 3.9 seconds with 250 km/h top speed, it offers razor-sharp handling from adaptive M suspension and active rear differential. Perfect balance of performance roadster dynamics with everyday usability.",
    features: [
      "3.0L BMW M TwinPower Turbo inline-six",
      "8-speed M Steptronic automatic",
      "M Adaptive suspension",
      "Active M Differential",
      "19-inch front / 20-inch rear M wheels",
      "M Sport brakes",
      "Laserlight headlights",
      "Vernova Blue brake calipers",
      "Heated sport seats",
      "Convertible soft top",
    ],
    highlights: [
      "382 HP @ 5800 rpm",
      "3.9s 0-100 km/h acceleration",
      "369 lb-ft @ 2650 rpm",
      "250 km/h top speed",
      "50:50 weight distribution",
    ],
    why_choose: [
      "Inline-six soundtrack perfection",
      "Supple yet precise chassis",
      "Open-air grand touring",
      "M Performance value",
      "Timeless roadster styling",
    ],
    specs: {
      passengers: 2,
      luggage: 1,
      transmission: "8-speed Automatic",
      doors: 2,
      engine: "3.0L Inline-6 Twin-Turbo",
      fuel_type: "Petrol",
      horsepower: "382 HP",
      acceleration: "3.9s 0-100 km/h",
      top_speed: "250 km/h",
      drive_type: "RWD",
    },
    has_chauffeur: false,
  },
  {
    slug: "bmw-x4-m-competition",
    display_name: "BMW X4 M Competition",
    brand: "BMW",
    model: "X4 M",
    variant: "Competition",
    model_year: 2026,
    category: "SUV",
    tags: ["suv-coupe", "m-performance", "competition", "sports"],
    location_default: "Dubai",
    main_image: "string",
    gallery_images: ["string"],
    thumbnail: null,
    description:
      "503 HP M4-sourced twin-turbo inline-six in fastest SUV coupe form.",
    long_description:
      "The BMW X4 M Competition unleashes 503 horsepower from its 3.0L twin-turbo S58 inline-six through an 8-speed M Steptronic transmission and M xDrive all-wheel drive. Achieving 0-100 km/h in 3.7 seconds with 290 km/h top speed, it features M adaptive suspension, massive M brakes, and active M differential. Track-capable SUV coupe seats five with 525L cargo space.",
    features: [
      "3.0L S58 twin-turbo inline-six",
      "8-speed M Steptronic automatic",
      "M xDrive all-wheel drive",
      "M adaptive suspension",
      "M Carbon ceramic brakes option",
      "21-inch M forged wheels",
      "M Sport exhaust",
      "M multifunctional seats",
      "Laserlight headlights",
      "M Head-up Display",
    ],
    highlights: [
      "503 HP @ 6250 rpm",
      "3.7s 0-100 km/h acceleration",
      "650 Nm @ 2750 rpm",
      "290 km/h top speed",
      "M4-derived powertrain",
    ],
    why_choose: [
      "Fastest production X4 ever",
      "M4 power in SUV practicality",
      "Track-capable daily driver",
      "Aggressive coupe-SUV styling",
      "Ultimate performance crossover",
    ],
    specs: {
      passengers: 5,
      luggage: 3,
      transmission: "8-speed Automatic",
      doors: 5,
      engine: "3.0L Inline-6 Twin-Turbo",
      fuel_type: "Petrol",
      horsepower: "503 HP",
      acceleration: "3.7s 0-100 km/h",
      top_speed: "290 km/h",
      drive_type: "AWD",
    },
    has_chauffeur: false,
  },
  {
    slug: "mercedes-benz-gle-450",
    display_name: "Mercedes-Benz GLE 450 4MATIC",
    brand: "Mercedes-Benz",
    model: "GLE",
    variant: "450 4MATIC",
    model_year: 2026,
    category: "SUV",
    tags: ["suv", "luxury", "mild-hybrid", "4matic"],
    location_default: "Dubai",
    main_image: "string",
    gallery_images: ["string"],
    thumbnail: null,
    description:
      "375 HP inline-six mild-hybrid luxury SUV with advanced air suspension.",
    long_description:
      "The Mercedes-Benz GLE 450 4MATIC features a 3.0L turbo inline-six with EQ Boost mild-hybrid producing 375 horsepower and 500 Nm torque through a 9-speed automatic and 4MATIC+ all-wheel drive. E-Active Body Control air suspension scans road imperfections 1,000x/min for unparalleled comfort. Seating five with 630L cargo space, it combines luxury, technology, and effortless performance.",
    features: [
      "3.0L inline-six turbo + 48V mild-hybrid",
      "9-speed 9G-TRONIC automatic",
      "4MATIC+ all-wheel drive",
      "E-Active Body Control suspension",
      "MBUX Hyperscreen option",
      "Burmester 4D surround sound",
      "Heated/ventilated massage seats",
      "360° camera with Off-Road View",
      "Active Distance Assist DISTRONIC",
      "Trailer Stability Assist",
    ],
    highlights: [
      "375 HP inline-six mild-hybrid",
      "5.7s 0-100 km/h acceleration",
      "500 Nm torque peak",
      "250 km/h top speed",
      "3,500 kg towing capacity",
    ],
    why_choose: [
      "Smooth inline-six refinement",
      "Advanced air suspension comfort",
      "Mild-hybrid efficiency boost",
      "Luxury meets technology",
      "Perfect family luxury SUV",
    ],
    specs: {
      passengers: 5,
      luggage: 4,
      transmission: "9-speed Automatic",
      doors: 5,
      engine: "3.0L Inline-6 Turbo Mild-Hybrid",
      fuel_type: "Petrol",
      horsepower: "375 HP",
      acceleration: "5.7s 0-100 km/h",
      top_speed: "250 km/h",
      drive_type: "AWD",
    },
    has_chauffeur: false,
  },
  {
    slug: "lamborghini-aventador-ultimae",
    display_name: "Lamborghini Aventador LP 780-4 Ultimae",
    brand: "Lamborghini",
    model: "Aventador",
    variant: "Ultimae",
    model_year: 2026,
    category: "Supercar",
    tags: ["supercar", "v12", "scissor-doors", "limited-edition"],
    location_default: "Dubai",
    main_image: "string",
    gallery_images: ["string"],
    thumbnail: null,
    description:
      "Final V12 evolution with 769 HP naturally aspirated fury and scissor door drama.",
    long_description:
      "The Lamborghini Aventador Ultimae delivers 769 horsepower from its screaming 6.5L naturally aspirated V12 through a 7-speed ISR single-clutch transmission and Haldex AWD. Lamborghini's final naturally aspirated V12 supercar achieves 0-100 km/h in 2.8 seconds with 355 km/h top speed. Limited to 350 coupes and 250 roadsters, it represents the ultimate expression of Aventador engineering with exposed carbon fiber and aggressive ALA 2.0 aerodynamics.",
    features: [
      "6.5L naturally aspirated V12",
      "7-speed ISR single-clutch auto",
      "Haldex all-wheel drive",
      "ALA 2.0 active aerodynamics",
      "Carbon fiber monocoque",
      "Scissor doors",
      "Forged composite wheels",
      "Carbon-ceramic brakes",
      "Alcantara/carbon interior",
      "15-inch central touchscreen",
    ],
    highlights: [
      "769 HP @ 8500 rpm V12",
      "2.8s 0-100 km/h acceleration",
      "531 lb-ft @ 6750 rpm",
      "355 km/h top speed",
      "Limited production finale",
    ],
    why_choose: [
      "Final naturally aspirated V12",
      "Iconic scissor door theater",
      "Track weapon with road presence",
      "Ultimate Lamborghini collectible",
      "Dubai supercar perfection",
    ],
    specs: {
      passengers: 2,
      luggage: 1,
      transmission: "7-speed Automatic",
      doors: 2,
      engine: "6.5L V12 Naturally Aspirated",
      fuel_type: "Petrol",
      horsepower: "769 HP",
      acceleration: "2.8s 0-100 km/h",
      top_speed: "355 km/h",
      drive_type: "AWD",
    },
    has_chauffeur: false,
  },
  {
    slug: "ferrari-purosangue",
    display_name: "Ferrari Purosangue",
    brand: "Ferrari",
    model: "Purosangue",
    variant: "V12",
    model_year: 2026,
    category: "SUV",
    tags: ["suv", "v12", "ferrari", "all-wheel-drive"],
    location_default: "Dubai",
    main_image: "string",
    gallery_images: ["string"],
    thumbnail: null,
    description:
      "Ferrari's first SUV with 715 HP V12, 4 seats, and Prancing Horse dynamics.",
    long_description:
      "Ferrari Purosangue combines a front-mid mounted 6.5L naturally aspirated V12 producing 715 horsepower and 528 lb-ft through 8-speed dual-clutch and all-wheel drive. Achieving 0-100 km/h in 3.3 seconds with 310+ km/h top speed, it features 4 individual seats, independent double-wishbone suspension at all wheels, and active aerodynamics. Ferrari's first 4-door production car redefines performance SUV engineering.",
    features: [
      "6.5L naturally aspirated V12",
      "8-speed dual-clutch automatic",
      "All-wheel drive system",
      "Independent double-wishbone suspension",
      "Active aero front flaps",
      "21-inch forged wheels",
      "Carbon-ceramic brakes",
      "Scuderia Ferrari shields",
      "4 individual bucket seats",
      "10.25-inch passenger display",
    ],
    highlights: [
      "715 HP @ 7750 rpm V12",
      "3.3s 0-100 km/h acceleration",
      "528 lb-ft @ 6250 rpm",
      "310+ km/h top speed",
      "Ferrari's first 4-seater",
    ],
    why_choose: [
      "Most powerful Ferrari V12 SUV",
      "True Ferrari driving dynamics",
      "Exclusive 4-door Prancing Horse",
      "Limited production prestige",
      "Ultimate Dubai status SUV",
    ],
    specs: {
      passengers: 4,
      luggage: 3,
      transmission: "8-speed Dual-Clutch",
      doors: 4,
      engine: "6.5L V12 Naturally Aspirated",
      fuel_type: "Petrol",
      horsepower: "715 HP",
      acceleration: "3.3s 0-100 km/h",
      top_speed: "310 km/h",
      drive_type: "AWD",
    },
    has_chauffeur: false,
  },
  {
    slug: "ferrari-roma",
    display_name: "Ferrari Roma",
    brand: "Ferrari",
    model: "Roma",
    variant: "V8",
    model_year: 2026,
    category: "Luxury",
    tags: ["coupe", "grand-tourer", "ferrari", "v8"],
    location_default: "Dubai",
    main_image: "string",
    gallery_images: ["string"],
    thumbnail: null,
    description:
      "612 HP twin-turbo V8 grand tourer blending Ferrari performance with elegant understatement.",
    long_description:
      "Ferrari Roma features mid-front mounted 3.9L twin-turbo V8 producing 612 horsepower and 561 lb-ft through 8-speed dual-clutch transmission and rear-wheel drive. Achieving 0-100 km/h in 3.4 seconds with 320+ km/h top speed, its e-Diff electronic differential and Side Slip Control deliver accessible supercar dynamics. Roma's 'Dolce Vita' design pays homage to 1950s/60s Roman elegance with modern GT usability.",
    features: [
      "3.9L twin-turbo V8 (F154BH)",
      "8-speed dual-clutch automatic",
      "Rear-wheel drive",
      "e-Diff electronic differential",
      "Side Slip Angle Control 6.1",
      "20-inch forged wheels",
      "Carbon-ceramic brakes",
      "Active aero front flaps",
      "Dual cockpit digital displays",
      "Magnetorheological dampers",
    ],
    highlights: [
      "612 HP @ 7500 rpm",
      "3.4s 0-100 km/h acceleration",
      "561 lb-ft @ 3000 rpm",
      "320+ km/h top speed",
      "Ferrari's most accessible GT",
    ],
    why_choose: [
      "Elegant understated Ferrari design",
      "Supple GT ride with track capability",
      "Accessible supercar performance",
      "2+2 usability for daily driving",
      "Perfect Dubai boulevard cruiser",
    ],
    specs: {
      passengers: 4,
      luggage: 2,
      transmission: "8-speed Dual-Clutch",
      doors: 2,
      engine: "3.9L V8 Twin-Turbocharged",
      fuel_type: "Petrol",
      horsepower: "612 HP",
      acceleration: "3.4s 0-100 km/h",
      top_speed: "320 km/h",
      drive_type: "RWD",
    },
    has_chauffeur: false,
  },
  {
    slug: "gmc-yukon-denali",
    display_name: "GMC Yukon Denali",
    brand: "GMC",
    model: "Yukon",
    variant: "Denali",
    model_year: 2026,
    category: "8Seater",
    tags: ["suv", "luxury", "v8", "towing"],
    location_default: "Dubai",
    main_image: "string",
    gallery_images: ["string"],
    thumbnail: null,
    description:
      "Premium full-size SUV with 420 HP V8, massive towing capacity, and luxury appointments.",
    long_description:
      "The 2026 GMC Yukon Denali features a 6.2L V8 producing 420 horsepower and 460 lb-ft through a 10-speed automatic transmission. Seating up to 8 passengers with 25.5 cu.ft. cargo behind third row (122.9 cu.ft. max), it offers 8,400 lbs towing capacity and available Air Ride Adaptive Suspension. Denali trim adds exclusive 22-inch wheels, open-pore wood, and 16-way massaging seats for ultimate American luxury.",
    features: [
      "6.2L EcoTec3 V8 engine",
      "10-speed automatic transmission",
      "Air Ride Adaptive Suspension",
      "Magnetic Ride Control",
      "22-inch polished aluminum wheels",
      "16-way power massaging front seats",
      "22-speaker Bose Performance audio",
      "Head-Up Display",
      "Night Vision (available)",
      "Super Cruise hands-free driving",
    ],
    highlights: [
      "420 HP 6.2L V8 engine",
      "8,400 lbs maximum towing",
      "122.9 cu.ft. maximum cargo",
      "Up to 8-passenger capacity",
      "0-60 mph in 6.0 seconds",
    ],
    why_choose: [
      "Ultimate towing capability",
      "Premium Denali luxury interior",
      "Advanced Super Cruise technology",
      "Massive family hauling capacity",
      "Bold American SUV presence",
    ],
    specs: {
      passengers: 8,
      luggage: 4,
      transmission: "10-speed Automatic",
      doors: 5,
      engine: "6.2L V8",
      fuel_type: "Petrol",
      horsepower: "420 HP",
      acceleration: "6.0s 0-100 km/h",
      top_speed: "130 mph",
      drive_type: "4WD",
    },
    has_chauffeur: false,
  },
  {
    slug: "ford-mustang-gt",
    display_name: "Ford Mustang GT",
    brand: "Ford",
    model: "Mustang",
    variant: "GT",
    model_year: 2026,
    category: "Sports",
    tags: ["coupe", "muscle-car", "v8", "pony-car"],
    location_default: "Dubai",
    main_image: "string",
    gallery_images: ["string"],
    thumbnail: null,
    description:
      "Iconic American muscle with 486 hp 5.0L V8 and pure pony car heritage.",
    long_description:
      "The 2026 Ford Mustang GT features Ford's legendary 5.0L Ti-VCT Coyote V8 producing 486 horsepower (with active exhaust) through a 10-speed automatic or 6-speed manual transmission. Achieving 0-100 km/h in approximately 4.2 seconds, it offers MagneRide adaptive dampers, Brembo brakes option, and distinctive tri-bar taillights. Pure analog driving pleasure meets modern performance technology.",
    features: [
      "5.0L Coyote Ti-VCT V8",
      "10-speed automatic or 6-speed manual",
      "Rear-wheel drive",
      "MagneRide damping system",
      "19-inch performance wheels",
      "Brembo brake option",
      "Digital instrument cluster",
      "12.4-inch SYNC 4 touchscreen",
      "B&O Sound System by Bang & Olufsen",
      "Active valve performance exhaust",
    ],
    highlights: [
      "486 HP 5.0L V8 (with exhaust)",
      "4.2s 0-100 km/h acceleration",
      "418 lb-ft torque",
      "250 km/h top speed",
      "Iconic Mustang styling",
    ],
    why_choose: [
      "Pure V8 muscle car experience",
      "Manual transmission option",
      "Affordable American performance",
      "Timeless pony car heritage",
      "Customizable personalization",
    ],
    specs: {
      passengers: 4,
      luggage: 2,
      transmission: "10-speed Automatic",
      doors: 2,
      engine: "5.0L V8",
      fuel_type: "Petrol",
      horsepower: "486 HP",
      acceleration: "4.2s 0-100 km/h",
      top_speed: "250 km/h",
      drive_type: "RWD",
    },
    has_chauffeur: false,
  },
  {
    slug: "mercedes-amg-gle63-s",
    display_name: "Mercedes-AMG GLE 63 S 4MATIC+",
    brand: "Mercedes-Benz",
    model: "GLE",
    variant: "AMG GLE 63 S",
    model_year: 2026,
    category: "SUV",
    tags: ["suv", "amg", "v8", "performance"],
    location_default: "Dubai",
    main_image: "string",
    gallery_images: ["string"],
    thumbnail: null,
    description:
      "603 HP hand-built twin-turbo V8 SUV with supercar acceleration and luxury.",
    long_description:
      "The Mercedes-AMG GLE 63 S 4MATIC+ features a hand-assembled 4.0L twin-turbo V8 with mild-hybrid producing 603 horsepower and 627 lb-ft through a 9-speed AMG Speedshift transmission and rear-biased 4MATIC+ AWD. Achieving 0-100 km/h in 3.9 seconds despite 2,500+ kg weight, it includes AMG Ride Control+, active rear axle steering, and massive carbon-ceramic brakes option. Ultimate performance SUV seats five with 655L cargo capacity.",
    features: [
      "Hand-built AMG 4.0L V8 biturbo + mild-hybrid",
      "AMG SPEEDSHIFT TCT 9G-TRONIC",
      "AMG Performance 4MATIC+ AWD",
      "AMG Ride Control+ adaptive suspension",
      "Active rear axle steering",
      "21/22-inch AMG forged wheels",
      "Carbon-ceramic brakes (option)",
      "Burmester High-End 3D surround sound",
      "MBUX Superscreen with AMG displays",
      "Massaging multicontour seats",
    ],
    highlights: [
      "603 HP @ 5750 rpm V8",
      "3.9s 0-100 km/h acceleration",
      "627 lb-ft @ 2500 rpm",
      "280 km/h top speed",
      "Tested 3.4s 0-60 mph",
    ],
    why_choose: [
      "Supercar acceleration in SUV form",
      "Hand-built AMG V8 soundtrack",
      "Track-capable luxury transporter",
      "Rear-biased AWD dynamics",
      "Ultimate Dubai performance SUV",
    ],
    specs: {
      passengers: 5,
      luggage: 4,
      transmission: "9-speed Automatic",
      doors: 5,
      engine: "4.0L V8 Twin-Turbo Mild-Hybrid",
      fuel_type: "Petrol",
      horsepower: "603 HP",
      acceleration: "3.9s 0-100 km/h",
      top_speed: "280 km/h",
      drive_type: "AWD",
    },
    has_chauffeur: false,
  },
  {
    slug: "jaguar-f-pace-p250",
    display_name: "Jaguar F-PACE P250 R-Dynamic S",
    brand: "Jaguar",
    model: "F-PACE",
    variant: "P250 R-Dynamic S",
    model_year: 2026,
    category: "SUV",
    tags: ["suv", "luxury", "performance", "all-wheel-drive"],
    location_default: "Dubai",
    main_image: "string",
    gallery_images: ["string"],
    thumbnail: null,
    description:
      "Refined British luxury SUV with 246 HP turbo-four, agile handling, and distinctive design.",
    long_description:
      "The Jaguar F-PACE P250 R-Dynamic S features a 2.0L turbocharged inline-four producing 246 horsepower and 269 lb-ft through an 8-speed automatic and intelligent AWD. Delivering 22/27 mpg EPA estimates with 613L boot space, it offers Jaguar's acclaimed chassis dynamics, premium Windsor leather interior, and Pivi Pro infotainment. Sophisticated luxury SUV blending sportiness with family practicality.",
    features: [
      "2.0L Ingenium turbocharged I4",
      "8-speed automatic transmission",
      "Intelligent All-Wheel Drive",
      "Adaptive Dynamics suspension",
      "19-inch gloss black alloy wheels",
      "Windsor leather sport seats",
      "Pivi Pro 11.4-inch touchscreen",
      "Meridian surround sound",
      "360° surround camera",
      "Adaptive Cruise Control",
    ],
    highlights: [
      "246 HP turbocharged engine",
      "22/27 mpg EPA city/highway",
      "613L boot capacity",
      "5-passenger luxury seating",
      "Premium British craftsmanship",
    ],
    why_choose: [
      "Exceptional handling dynamics",
      "Distinctive Jaguar design",
      "Luxurious Windsor leather interior",
      "Advanced Pivi Pro technology",
      "Perfect balance of sport and luxury",
    ],
    specs: {
      passengers: 5,
      luggage: 4,
      transmission: "8-speed Automatic",
      doors: 5,
      engine: "2.0L Turbocharged I4",
      fuel_type: "Petrol",
      horsepower: "246 HP",
      acceleration: "6.9s 0-100 km/h",
      top_speed: "217 km/h",
      drive_type: "AWD",
    },
    has_chauffeur: false,
  },
  {
    slug: "nissan-xterra",
    display_name: "Nissan X-Terra SE 4x4",
    brand: "Nissan",
    model: "X-Terra",
    variant: "SE 4x4",
    model_year: 2026,
    category: "7Seater",
    tags: ["suv", "4x4", "off-road", "7-seater"],
    location_default: "Dubai",
    main_image: "string",
    gallery_images: ["string"],
    thumbnail: null,
    description:
      "Rugged 7-seat 4x4 SUV with off-road capability and family practicality.",
    long_description:
      "The Nissan X-Terra features a proven 2.5L 4-cylinder petrol engine producing 165 horsepower and 241 Nm torque through an automatic transmission and available 4x4 system. Designed for Middle East markets, it offers 7-passenger seating, 78L fuel tank, and genuine off-road features including Hill Descent Control and rear differential lock. Tough body-on-frame construction handles desert adventures while providing family transport capability.",
    features: [
      "2.5L 4-cylinder petrol engine",
      "Automatic transmission",
      "Part-time 4WD system",
      "Hill Descent Control",
      "Rear differential lock",
      "17-inch alloy wheels",
      "7-inch driver display",
      "Rear parking sensors",
      "Rearview camera",
      "Cruise control",
    ],
    highlights: [
      "165 HP 2.5L engine",
      "7-passenger seating",
      "78L fuel tank capacity",
      "Off-road 4x4 capability",
      "Body-on-frame construction",
    ],
    why_choose: [
      "Proven Middle East durability",
      "Genuine 4x4 off-road ability",
      "Spacious 7-seat configuration",
      "Large fuel capacity for adventures",
      "Affordable rugged SUV",
    ],
    specs: {
      passengers: 7,
      luggage: 4,
      transmission: "Automatic",
      doors: 5,
      engine: "2.5L I4",
      fuel_type: "Petrol",
      horsepower: "165 HP",
      acceleration: "11s 0-100 km/h",
      top_speed: "190 km/h",
      drive_type: "4WD",
    },
    has_chauffeur: false,
  },
];
